import { useState, useEffect, useCallback } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Intro from '../../../../components/Editar Perfil/Intro'
import Body from '../../../../components/Editar Perfil/Body'
//import Navbar from '../../../components/Layout/Navbar'
import Navbar from '../../../../components/Layout/NavbarLogged'
import Sidebar from '../../../../components/Layout/Sidebar'
import Footer from '../../../../components/Layout/Footer'
import styles from '../../../../styles/style'
import { menu, close } from '../../../../assets/index'
import { getDoc, doc, getFirestore, getDocs, query, where, collection } from "firebase/firestore"
import { app } from '../../../../config'
import { Circles } from 'react-loader-spinner'
import Loader from '../../../../components/Layout/Loader'

export default function Editar() {

  const router = useRouter();

  const [toggle, setToggle] = useState(false)

  const [active, setActive] = useState(false)

  const [usuario, setUsuario] = useState({})
  const [anuncios, setAnuncios] = useState({})

  const [loading, setLoading] = useState(true)

  const changeBackground = () => {
    if (window.scrollY >= 80) {
      setActive(true)
    } else {
      setActive(false)
    }
  }

  useEffect(() => {
    window.addEventListener('scroll', changeBackground)
  }, []);

  const db = getFirestore(app);
  useEffect(() => {
    const getAnuncio = async () => {
      const userInfo = localStorage.getItem('user') !== 'undefined' ? JSON.parse(localStorage.getItem('user')) : localStorage.clear()
      try {
        const userID = router.query.id
        const docRef = doc(db, "users", userID);
        const docSnap = await getDoc(docRef);
        console.log("Document data:", docSnap.data());
        setUsuario(docSnap.data())
        console.log(usuario)
        const itemsRef = query(collection(db, 'anuncios'), where('active', '==', true), where('createdBy', '==', router.query.id))
        const querySnapshot = await getDocs(itemsRef)
        const data = querySnapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }))
        setAnuncios(data)
        console.log("Anuncios data:", data);
        setLoading(false)
      } catch (e) {
        console.log(e)
      }
      if(router.query.id !== userInfo.uid) {
        router.push('/market/mi-perfil')
      }
    }
    getAnuncio()
  }, [router.isReady])

  const [isLogged, setIsLogged] = useState(true)
  useEffect(() => {
    const userInfo = localStorage.getItem('user') !== 'undefined' ? JSON.parse(localStorage.getItem('user')) : localStorage.clear()
    if(!userInfo) {
      setIsLogged(false)
      router.push('/acceder')
    }
  }, [])

  if (!isLogged) {
    return <div className='w-full overflow-hidden'>
          <div className={`${styles.flexStart} sm:mt-[7.5rem] mt-20`}>
            <div className={`${styles.boxWidth}`}>
              <Loader />
            </div>
          </div>
    </div>
  }

  return (
    <>
      <Head>
        <title>LibreCripto | Editar Mi Perfil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={`fixed w-full max-w-[1920px] m-auto z-40 bg-black sidebar-shadow`}>
          <div className={`sm:px-60 px-12 ${styles.flexCenter} gap-5`}>
            <img className='xs:flex hidden w-[28px] h-[28px] object-contain cursor-pointer' onClick={() => setToggle((prev) => !prev)} src={toggle ? close.src : menu.src} alt="menu"></img>
            <Navbar title="Editar Mi Perfil" />
            <img className='xs:hidden flex  w-[28px] h-[28px] object-contain cursor-pointer' onClick={() => setToggle((prev) => !prev)} src={toggle ? close.src : menu.src} alt="menu"></img>
          </div>
        </div>
        <div className={`${toggle ? 'flex' : 'hidden'} fixed h-full max-w-[1920px] m-auto z-40 bg-black sidebar-shadow`}>
          <div className={`px-5 ${styles.flexCenter}`}>
            <Sidebar />
          </div>
        </div>
      </header>
      <main>
        <div className='bg-black w-full overflow-hidden sm:[z-0]'>
          <div className={`bg-black ${styles.flexStart} sm:mt-[7.5rem] mt-20 sm:hidden`}>
            <div className={`${styles.boxWidth}`}>
              <Intro />
            </div>
          </div>
          <div className={`bg-black ${styles.paddingX} ${styles.flexStart}`}>
            <div className={`${styles.boxWidth}`}>
              <Body
                image={usuario.image}
                userName={usuario.name}
                userEmail = {usuario.email}
                userPhone = {usuario.phone}
                createdAt={usuario.createdAt}
                totalOperations={usuario.totalOperations}
                lastOperationDate={usuario.lastOperationDate}
                operationsPunctuation={usuario.operationsPunctuation}
                description={usuario.desc}
                load={loading}
                anuncios={anuncios}
                userID={usuario.uid}
              />
            </div>
          </div>
          <div className={`bg-orange ${styles.paddingX} ${styles.flexStart}`}>
            <div className={`${styles.boxWidth}`}>
              <Footer />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}