import { useEffect, useCallback } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Intro from '../../../components/Anuncio/Intro'
import Body from '../../../components/Perfil/Body'
//import Navbar from '../../components/Layout/Navbar'
import Navbar from '../../../components/Layout/NavbarLogged'
import Sidebar from '../../../components/Layout/Sidebar'
import Footer from '../../../components/Layout/Footer'
import styles from '../../../styles/style'
import { menu, close } from '../../../assets/index'
import { getDoc, doc, getFirestore, getDocs, query, where, collection } from "firebase/firestore"
import { app } from '../../../config'
import { Circles } from 'react-loader-spinner'
import Loader from '../../../components/Layout/Loader'
import useState from 'react-usestateref'

export default function AnuncioLayout() {

  const router = useRouter();

  const [toggle, setToggle] = useState(false)

  const [active, setActive] = useState(false)

  const [usuario, setUsuario, usuarioRef] = useState({})
  const [anuncios, setAnuncios] = useState({})

  const [loading, setLoading] = useState(true)

  const changeBackground = () => {
    if (window.scrollY >= 80) {
      setActive(true)
    } else {
      setActive(false)
    }
  }

  useEffect(() => {
    window.addEventListener('scroll', changeBackground)
  }, []);

  const db = getFirestore(app);
  useEffect(() => {
    const getAnuncio = async () => {
      const userInfo = localStorage.getItem('user') !== 'undefined' ? JSON.parse(localStorage.getItem('user')) : localStorage.clear()
      try {
        const userID = router.query.id
        const xRef = query(collection(db, 'users'), where('publicID',  '==', userID))
        const xQuerySnapshot = await getDocs(xRef)
        const xData = xQuerySnapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }))
        setAnuncios(xData)
        console.log("User data:", xData);
        //const docRef = doc(db, "users", "SpAUgjZCqggw63BZDQiZFGG21lm1");
        //const docSnap = await getDoc(docRef);
        //console.log("Document data:", docSnap.data());
        setUsuario(xData[0])
        console.log(usuarioRef.current)
        if (usuarioRef.current !== '') {
          const itemsRef = query(collection(db, 'anuncios'), where('active', '==', true), where('createdBy', '==', usuarioRef.current?.uid))
          const querySnapshot = await getDocs(itemsRef)
          const data = querySnapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }))
          setAnuncios(data)
          console.log("Anuncios data:", data);
          setLoading(false)
        } else {
          console.log('it is undefined')
        }
      } catch (e) {
        console.log(e)
      }
      if(usuarioRef.current?.uid == userInfo.uid) {
        router.push('/market/mi-perfil')
      }
    }
    getAnuncio()
  }, [router.isReady])

  const [isLogged, setIsLogged] = useState(true)
  useEffect(() => {
    const userInfo = localStorage.getItem('user') !== 'undefined' ? JSON.parse(localStorage.getItem('user')) : localStorage.clear()
    if(!userInfo) {
      setIsLogged(false)
      router.push('/acceder')
    }
  }, [])

  if (!isLogged) {
    return <div className='w-full overflow-hidden'>
          <div className={`${styles.flexStart} sm:mt-[7.5rem] mt-20`}>
            <div className={`${styles.boxWidth}`}>
              <Loader />
            </div>
          </div>
    </div>
  }

  return (
    <>
      <Head>
        <title>LibreCripto | Perfil de {usuarioRef.current.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={`fixed w-full max-w-[1920px] m-auto z-40 bg-black sidebar-shadow`}>
          <div className={`sm:px-60 px-12 ${styles.flexCenter} gap-5`}>
            <img className='xs:flex hidden w-[28px] h-[28px] object-contain cursor-pointer' onClick={() => setToggle((prev) => !prev)} src={toggle ? close.src : menu.src} alt="menu"></img>
            <Navbar />
            <img className='xs:hidden flex  w-[28px] h-[28px] object-contain cursor-pointer' onClick={() => setToggle((prev) => !prev)} src={toggle ? close.src : menu.src} alt="menu"></img>
          </div>
        </div>
        <div className={`${toggle ? 'flex' : 'hidden'} fixed h-full max-w-[1920px] m-auto z-40 bg-black sidebar-shadow`}>
          <div className={`px-5 ${styles.flexCenter}`}>
            <Sidebar />
          </div>
        </div>
      </header>
      <main>
        <div className='bg-black w-full overflow-hidden sm:[z-0]'>
          <div className={`bg-black flex flex-col justify-center items-start`}>
            <div className={`bg-orange ${styles.paddingX} ${styles.flexStart} h-[25vh] w-full`}></div>
            <div className={`${styles.paddingX} flex justify-between items-start m-auto`}>
            <div className={`${styles.boxWidth}`}>
            {loading ? 
                <div className='h-screen flex items-center justify-center'>
                  <div className='m-auto w-full flex flex-wrap flex-col items-center justify-center'>
                    <Circles height="70" width="70" color="#fe9416" ariaLabel="circles-loading" wrapperStyle={{}} wrapperClass="" visible={true} /> 
                    <p className='text-white mt-5'>Cargando información del usuario...</p>
                  </div>
                </div>
                :
                <Body
                    image={usuarioRef.current.image}
                    userName={usuarioRef.current.name}
                    createdAt={usuarioRef.current.createdAt}
                    totalOperations={usuarioRef.current.totalOperations}
                    lastOperationDate={usuarioRef.current.lastOperationDate}
                    operationsPunctuation={usuarioRef.current.operationsPunctuation}
                    description = {usuarioRef.current.desc}
                    load = {loading}
                    anuncios = {anuncios}
                    userID ={usuarioRef.current.uid}
                />}
            </div>
            </div>
          </div> 
          <div className={`bg-orange ${styles.paddingX} ${styles.flexStart}`}>
            <div className={`${styles.boxWidth}`}>
              <Footer />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}